name: Go Build and Release

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build the Go app
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o my-app-${{ matrix.goos }}-${{ matrix.goarch }} ./...
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-app-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ./my-app-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v2
    - name: Create GitHub Release
      uses: gh-actions/gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        assets: ./*
